# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 08:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 10, 8, 18, 23, 434218, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
