# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20171010_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(blank=True, default=None, editable=False, max_length=320, null=True),
        ),
    ]
