# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_vacancy_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='header_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=b'vacancy-header-images'),
        ),
    ]
